### ISSUE TITLE
Clarify under what license this library is being released

### ISSUE THREAD

**Issue by spemmons** [cristianstaicu/eval-sanitizer#1]
Nice package, but it would help if you could stipulate the license under which this code is being distributed. Perhaps MIT license? https://opensource.org/licenses/MIT

**Comment by cristianstaicu** [comment]
I am happy that you see the potential in this package / idea. Thank you for submitting this issue! I've published a new version including the license (BSD-3-Clause). I am happy to welcome any contribution to the package if it proves to be a meaningful one!
